# Site settings
title: Ferme de l'Ecurieux
email: contact@ferme-de-l-ecurieux.fr
description: > # this means to ignore newlines until "baseurl:"
  Ce site vous présente notre gîte et nos centres d'intérêt.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ferme-de-l-ecurieux.fr" # the base hostname & protocol for your site
twitter_username: ferme-de-l-ecurieux
github_username:  ferme-de-l-ecurieux

# Build settings
markdown: kramdown
